import { Artwork } from "./Artwork";
import { instance } from "./ArtworkDetail";

export const fetchArtwork = async (id: any) => {
  const fields = [
    "id",
    "title",
    "image_id",
    "artist_display",
    "publication_history",
    "exhibition_history",
    "provenance_text",
    "inscriptions",
    "api_model ",
    "api_link ",
    "is_boosted ",
    "alt_titles ",
    "thumbnail ",
    "main_reference_number ",
    "has_not_been_viewed_much ",
    "boost_rank ",
    "date_start ",
    "date_end ",
    "date_display ",
    "date_qualifier_title ",
    "date_qualifier_id ",
    "place_of_origin ",
    "dimensions ",
    "medium_display ",
    "inscriptions ",
    "credit_line ",
    "publication_history ",
    "exhibition_history ",
    "provenance_text ",
    "publishing_verification_level ",
    "internal_department_id ",
    "fiscal_year ",
    "fiscal_year_deaccession ",
    "is_public_domain ",
    "is_zoomable ",
    "max_zoom_window_size ",
    "copyright_notice ",
    "has_multimedia_resources ",
    "has_educational_resources ",
    "colorfulness ",
    "color ",
    "latitude ",
    "longitude ",
    "latlon ",
    "is_on_view ",
    "on_loan_display ",
    "gallery_title",
    "gallery_id ",
    "artwork_type_title ",
    "artwork_type_id ",
    "department_title ",
    "department_id ",
    "artist_id ",
    "artist_title ",
    "alt_artist_ids ",
    "artist_ids ",
    "artist_titles ",
    "category_ids ",
    "category_titles ",
    "artwork_catalogue_ids ",
    "term_titles ",
    "style_id ",
    "style_title ",
    "alt_style_ids ",
    "style_ids ",
    "style_titles ",
    "classification_id ",
    "classification_title ",
    "alt_classification_ids ",
    "classification_ids ",
    "classification_titles ",
    "subject_id ",
    "alt_subject_ids ",
    "subject_ids ",
    "subject_titles ",
    "material_id ",
    "alt_material_ids ",
    "material_ids ",
    "material_titles ",
    "technique_id ",
    "alt_technique_ids ",
    "technique_ids ",
    "technique_titles ",
    "theme_titles ",
    "image_id ",
    "alt_image_ids ",
    "alt_image_ids ",
    "document_ids ",
    "sound_ids",
    "video_ids ",
    "text_ids ",
    "section_ids ",
    "section_titles ",
    "site_ids ",
    "suggest_autocomplete_boosted ",
    "suggest_autocomplete_all ",
    "last_updated_source ",
    "last_updated ",
    "timestamp ",
  ]
    .join(",")
    .replaceAll(" ", "");

  const { data } = await instance.get<{ data: Artwork[]; }>("/artworks", {
    params: {
      ids: [id].join(","),
      fields: fields,
    },
  });
  return data.data[0];
};
